// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workshop.DataLayer.DataObjects;

namespace Workshop.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220605184523_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Controllers.MarketController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PRODUCT_COUNT")
                        .HasColumnType("int");

                    b.Property<int>("STORE_COUNT")
                        .HasColumnType("int");

                    b.Property<int?>("orderHandlerId")
                        .HasColumnType("int");

                    b.Property<int?>("userControllerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("orderHandlerId");

                    b.HasIndex("userControllerId");

                    b.ToTable("marketController");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Controllers.UserController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("notificationHandlerId")
                        .HasColumnType("int");

                    b.Property<int?>("orderHandlerId")
                        .HasColumnType("int");

                    b.Property<int?>("reviewHandlerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("notificationHandlerId");

                    b.HasIndex("orderHandlerId");

                    b.HasIndex("reviewHandlerId");

                    b.ToTable("userController");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.DiscountPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("DiscountPolicy");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Store")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ProductDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderDTOid")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDTOid");

                    b.ToTable("ProductDTO");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.PurchasePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("PurchasePolicy");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ShoppingBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingBag");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ShoppingBagProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingBagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingBagId");

                    b.ToTable("ShoppingBagProduct");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscountPolicyId")
                        .HasColumnType("int");

                    b.Property<int?>("MarketControllerId")
                        .HasColumnType("int");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<int?>("PurchasePolicyId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountPolicyId");

                    b.HasIndex("MarketControllerId");

                    b.HasIndex("PurchasePolicyId");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Members.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Members.Member", b =>
                {
                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<int?>("UserControllerId")
                        .HasColumnType("int");

                    b.HasKey("MemberName");

                    b.HasIndex("ShoppingCartId");

                    b.HasIndex("UserControllerId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Members.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MemberName");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Notifications.NotificationHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("NotificationHandler");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.MemberToOrders<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderHandler<int>Id")
                        .HasColumnType("int");

                    b.Property<int>("key")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHandler<int>Id");

                    b.ToTable("MemberToOrders<int>");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.MemberToOrders<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderHandler<string>Id")
                        .HasColumnType("int");

                    b.Property<string>("key")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderHandler<string>Id");

                    b.ToTable("MemberToOrders<string>");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.OrderDTO", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MemberToOrders<int>Id")
                        .HasColumnType("int");

                    b.Property<int?>("MemberToOrders<string>Id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("storeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("MemberToOrders<int>Id");

                    b.HasIndex("MemberToOrders<string>Id");

                    b.ToTable("OrderDTO");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.OrderHandler<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("OrderHandler<int>");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.OrderHandler<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("OrderHandler<string>");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Reviews.ReviewHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("ReviewHandler");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Controllers.MarketController", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.OrderHandler<int>", "orderHandler")
                        .WithMany()
                        .HasForeignKey("orderHandlerId");

                    b.HasOne("Workshop.DataLayer.DataObjects.Controllers.UserController", "userController")
                        .WithMany()
                        .HasForeignKey("userControllerId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Controllers.UserController", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Notifications.NotificationHandler", "notificationHandler")
                        .WithMany()
                        .HasForeignKey("notificationHandlerId");

                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.OrderHandler<string>", "orderHandler")
                        .WithMany()
                        .HasForeignKey("orderHandlerId");

                    b.HasOne("Workshop.DataLayer.DataObjects.Reviews.ReviewHandler", "reviewHandler")
                        .WithMany()
                        .HasForeignKey("reviewHandlerId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.Product", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Market.Store", null)
                        .WithMany("Products")
                        .HasForeignKey("StoreId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ProductDTO", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.OrderDTO", null)
                        .WithMany("items")
                        .HasForeignKey("OrderDTOid");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ShoppingBag", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Market.ShoppingCart", null)
                        .WithMany("ShoppingBags")
                        .HasForeignKey("ShoppingCartId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.ShoppingBagProduct", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Market.ShoppingBag", null)
                        .WithMany("Products")
                        .HasForeignKey("ShoppingBagId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Market.Store", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Market.DiscountPolicy", "DiscountPolicy")
                        .WithMany()
                        .HasForeignKey("DiscountPolicyId");

                    b.HasOne("Workshop.DataLayer.DataObjects.Controllers.MarketController", null)
                        .WithMany("stores")
                        .HasForeignKey("MarketControllerId");

                    b.HasOne("Workshop.DataLayer.DataObjects.Market.PurchasePolicy", "PurchasePolicy")
                        .WithMany()
                        .HasForeignKey("PurchasePolicyId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Members.Action", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Members.Role", null)
                        .WithMany("Actions")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Members.Member", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Market.ShoppingCart", "ShoppingCart")
                        .WithMany()
                        .HasForeignKey("ShoppingCartId");

                    b.HasOne("Workshop.DataLayer.DataObjects.Controllers.UserController", null)
                        .WithMany("members")
                        .HasForeignKey("UserControllerId");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Members.Role", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Members.Member", null)
                        .WithMany("Roles")
                        .HasForeignKey("MemberName");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.MemberToOrders<int>", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.OrderHandler<int>", null)
                        .WithMany("MemberToOrders")
                        .HasForeignKey("OrderHandler<int>Id");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.MemberToOrders<string>", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.OrderHandler<string>", null)
                        .WithMany("MemberToOrders")
                        .HasForeignKey("OrderHandler<string>Id");
                });

            modelBuilder.Entity("Workshop.DataLayer.DataObjects.Orders.OrderDTO", b =>
                {
                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.MemberToOrders<int>", null)
                        .WithMany("orders")
                        .HasForeignKey("MemberToOrders<int>Id");

                    b.HasOne("Workshop.DataLayer.DataObjects.Orders.MemberToOrders<string>", null)
                        .WithMany("orders")
                        .HasForeignKey("MemberToOrders<string>Id");
                });
#pragma warning restore 612, 618
        }
    }
}
